stages:
  - build
  - test

build-job:
  stage: build
  tags: 
    - devops_pipeline
  script:
    - echo "Compiling the code..."
    - echo "Compile complete." 

test-job:
  stage: test
  tags: 
    - devops_pipeline
  dependencies: 
    - build-job  
  script:
    - ls -al
    - echo "Running tests"