image: python:latest

stages:
  - static_analysis
  - test
  - deploy



flake-job:
  stage: static_analysis
  image: ubuntu:latest
  allow_failure: true
  before_script:
    - apt-get update -qq
    - apt-get install flake8
    - apt-get install python3
  only:
    - project
  script:
    - flake8 --ignore=E501 .

pylint:
  stage: static_analysis
  only:
    - project
  allow_failure: true
  before_script:
  - apt-get install pylint
  script:
    - pylint --fail-under=8 project

test-job:
  stage: test
  image: python:latest
  before_script:
    - pip install pytest
    - pip install pytest-mock
    - pip install fastapi
    - pip install pika
    - pip install PyLog2html
    - pip install python-dotenv
    - pip install "uvicorn[standard]"
    - export ENV=TEST

  script:
    - echo "Running tests"
    - cd tests/
    - pytest .
    - echo "test completed"
    


deploy_staging:
  image: ubuntu:latest
  stage: deploy
  before_script:
    #installing the required packages
    - apt-get update -qq
    - apt-get install -qq git
    - apt-get install sshpass
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    

  script:
    - echo "ssh deploy started"
    # ssh into the deployment using password, set the environment variable to PROD, create a new folder clone the repository using the access token and start the docker containers. 
    - sshpass -p root ssh root@deployment "rm -rf app && export ENV=PROD &&mkdir app && cd app && git clone http://prabu:glpat-L23Zfs9ed1cvDUsG5iQX@gitlab-ce/gitlab-instance-492260da/finalproject.git -b project && cd finalproject && docker-compose up --build -d && exit"
    - echo "ssh deploy completed"
  only:
    - project

