image: python:latest

stages:
  - build
  - test
  - deploy



build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete." 

test-job:
  stage: test
  dependencies: 
    - build-job  
  script:
    - ls -al
    - echo "Running tests"


deploy_staging:
  stage: deploy
  before_script:
  - echo "$SSH_PRIVATE_KEY"
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "ssh deploy started"
    - ssh prabu@localhost "cd var/www/ && git checkout project && git pull origin project && exit"
    - echo "ssh deploy completed"
  only:
    - project

