version: "3.2"
services:
  httpserver:
    build: httpserver/.
    container_name: httpserver
    expose:
      - "8083"
    ports:
      - "8083:8083"
    tty: true
    
    networks:
      backend:
    volumes:
      - web_data:/usr/data:ro
      - ./logs:/usr/logs
    depends_on:
      - rabitmq
  
  imed:
    build: imed/.
    container_name: imed
    depends_on:
      - rabitmq
    networks:
      backend:
    tty: true
    volumes:
      - ./logs:/usr/logs


  orig:
    build: orig/.
    container_name: orig
    tty: true
    networks:
      backend:
    depends_on:
      - rabitmq
    volumes:
      - ./logs:/usr/logs

  observ:
    build: observ/.
    tty: true   
    networks:
      backend:
    volumes:
      - web_data:/usr/data
      - ./logs:/usr/logs
    depends_on:
      - rabitmq
    container_name: observ
    
  rabitmq:
    image: rabbitmq:3.10-management
    container_name: rabitmq
    networks:
      backend:

networks:
 backend:
    name: backend-network
volumes:
  web_data: