version: "3.2"
services:
  httpserver:
    build: httpserver/.
    container_name: httpserver
    expose:
      - "8083"
    ports:
      - "8083:8083"
    tty: true
    env_file:
      - .env
    
    networks:
      backend:
    volumes:
      - ./web_data:/usr/data
      - ./logs:/usr/logs
    depends_on:
      - rabitmq
      - log_monitor
    
  
  imed:
    build: imed/.
    container_name: imed
    depends_on:
      - rabitmq
      - log_monitor
    networks:
      backend:
    tty: true
    volumes:
      - ./logs:/usr/logs
      - ./web_data:/usr/data
    env_file:
      - .env


  orig:
    build: orig/.
    container_name: orig
    tty: true
    networks:
      backend:
    depends_on:
      - rabitmq
      - log_monitor
    volumes:
      - ./logs:/usr/logs
      - ./web_data:/usr/data
    env_file:
      - .env

  observ:
    build: observ/.
    tty: true   
    networks:
      backend:
    volumes:
      - ./web_data:/usr/data
      - ./logs:/usr/logs
    depends_on:
      - rabitmq
      - log_monitor
    container_name: observ
    env_file:
      - .env

  log_monitor:
    build: log_monitor/.
    tty: true   
    networks:
      backend:
    expose:
      - "9999"
    ports:
      - "9999:9999"
    volumes:
      - ./logs:/usr/logs
    container_name: log_monitor
    env_file:
      - .env
    
  rabitmq:
    image: rabbitmq:3.10-management
    container_name: rabitmq
    networks:
      backend:

networks:
 backend:
    name: backend-network
volumes:
  web_data: